spring:
  application:
    name: notification-service
  config:
    import: optional:configserver:http://config-server:8888
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: org.example.*
        spring.json.value.default.type: org.example.notification.dto.UserEvent
  mail:
    host: mailhog
    port: 1025
    username: ""
    password: ""
    properties:
      mail.smtp.auth: false
      mail.smtp.starttls.enable: false
    test-connection: false

app:
  kafka:
    user-events-topic: user-events

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
      register-with-eureka: true
