server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  mail:
    host: 127.0.0.1
    port: 2525
    username:
    password:
    properties:
      mail.smtp.auth: false
      mail.smtp.starttls.enable: false
    test-connection: false