spring:
  kafka:
    bootstrap-servers: kafka:9092
  mail:
    host: mailhog
    port: 1025

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
    register-with-eureka: true
  instance:
    prefer-ip-address: true
